;; Sound Effects for song Sound effects, version 2.0, generated by Arkos Tracker 2.

;; The sound effects, starting at 1.
	dw note_SoundEffects_Sound1	;; Sound effect 1. ;; Sound effect 1.

note_SoundEffects_Sound1:
	db #0x00	;; Speed

note_SoundEffects_Sound1_Loop:	db #0x3D	;; Soft only. Volume: 15.
	dw #0x00EF	;; Software period.

	db #0x39	;; Soft only. Volume: 14.
	dw #0xEF	;; Software period.

	db #0x36	;; Soft only. Volume: 13.
	dw #0xEF	;; Software period.

	db #0x31	;; Soft only. Volume: 12.
	dw #0xEF	;; Software period.

	db #0x2D	;; Soft only. Volume: 11.
	dw #0xEF	;; Software period.

	db #0x29	;; Soft only. Volume: 10.
	dw #0xEF	;; Software period.

	db #0x25	;; Soft only. Volume: 9.
	dw #0xEF	;; Software period.

	db #0x21	;; Soft only. Volume: 8.
	dw #0xEF	;; Software period.

	db #0x1D	;; Soft only. Volume: 7.
	dw #0xEF	;; Software period.

	db #0x19	;; Soft only. Volume: 6.
	dw #0xEF	;; Software period.

	db #0x15	;; Soft only. Volume: 5.
	dw #0xEF	;; Software period.

	db #0x11	;; Soft only. Volume: 4.
	dw #0xEF	;; Software period.

	db #0x0D	;; Soft only. Volume: 3.
	dw #0xEF	;; Software period.

	db #0x9	;; Soft only. Volume: 2.
	dw #0xEF	;; Software period.

	db #0x5	;; Soft only. Volume: 1.
	dw #0xEF	;; Software period.

	db #0x4	;; End of the sound effect.

note_SoundEffectsDisarkByteRegionEnd1:


;; Sound effect 1.
Soundeffects_Subsong_SoundEffect1:
        db #0x0    ;; Speed.
Soundeffects_Subsong_SoundEffect1_Loop:	db #0xBD	;; Soft only. Volume: 15.
	db #0x1	;; Noise: 1.
	dw #0x5F	;; Software period.

	db #0xBD	;; Soft only. Volume: 15.
	db #0x1	;; Noise: 1.
	dw #0x63	;; Software period.

	db #0xB1	;; Soft only. Volume: 12.
	db #0x1	;; Noise: 1.
	dw #0x66	;; Software period.

	db #0xAD	;; Soft only. Volume: 11.
	db #0x1	;; Noise: 1.
	dw #0x6A	;; Software period.

	db #0x4	;; End of the sound effect.


